# Generated by Django 3.0.7 on 2020-08-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200824_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='published_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
