# Generated by Django 3.0.7 on 2020-08-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20200824_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='updated_at',
            new_name='updated_time',
        ),
    ]
